baseURL = ""
languageCode = "en-us"
title = "What I Think"
theme = "my-elephants"
googleAnalytics = "UA-96078689-5"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

[params]
  sitename = "What I think"
