baseURL = "http://example.org/"
languageCode = "en-us"
title = "What I Think"
theme = "yinyang"

[author]
	name = "What I Think"
	homepage = "https://aunnnn.com"


[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1


[[params.socials]]
name = "About Me"
link = "https://aunnnn.com"

[[params.socials]]
name = "Github"
link = "https://github.com/aunnnn"